language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- python setup.py install
script:
- pytest
- cd test
- "./test.sh subcommandstest"
- for i in `ls subcommandstest_run_*/*.log`;do echo $i;egrep -i "error|warning" $i;
  done; [ $? == 1 ] || false
- cd ..
deploy:
  provider: pypi
  user:
    secure: r69xkNziRYZQL61MPB4W2O4pUlfJN5ep+96i2s1xRMZ0lxx1gbDRli0vWsyLLVldIrQgxx3k3NYcNP65LspeT8x/Fxfe+Xbl8hkGSujCBNxdAXq++/kDB8htfIHHYCZ7TzzyiOe+8rXSEogPzi0zlLfDz5qnd+xbMaJ1ysxGUxf1x6lYg+bjC2H06tRjb87CWJRqvlF3gAyyVNQxpyEuJBs8E9VQwvgfU6S4PS1zI0eHIzBmbJidSF0k36l3FA0ji3t0ovPhidWch3hs4Ol1yvL6/GUzw0QO065RFGB9jSqQ4Gv+Ef09tviMx/NP7SZ/sD8MMJUSwo/6NZsbQjMLAqdelBtWMUPYqxVBTqRg2sC1aeiSw1UmEeKsu5hAO61C8Tc/GM/RFCJGUONyZkqWOlP0QJ6VEfnfGjcjr/nsthqS0za4ZGKksvJB6HCDvXTGjEyLfdmbHcSbxmm1m6+JoUFPN66mF7SAmg4dah845HOTym/103q8r35Eb7QevHlh1qtcjK1Mbxi2mUgNdjJjVA2SU8lBi8YgUx/9acmnXZLv/39x2mVcPLV7mJNFaPK2s/5zsddYJKzc15wb+oSuQmy5OXS0GwywNeQeu4MpHhQfhV0sUOza2IOxcVrIbXbCxZS7XuX10NShuR8CXVTnmJMIuYj5rpBb/HAJiWOmFso=
  password:
    secure: H2/hfeKP2gPkPbRB0Hnsit+gppDVyWfdcokHXjjV9YReIXQHaFYj0l0tv+cjVDClkS0msnW+i2ZGH+zESc9kCBI8SXj9mpnIMS+yCFwk41U7U7NDV3wgZyP2n7g3ISXXOZwnARFWS1DsO6hE5qTxNq4kdOWrYTXbBWF8UGO0+po3NlfSt2bhlKci0tAyVhaoX8h0L/krzf9oJ4DvzSNOdHGLl/uuH9UdkHjz2xiqF/l/4szSblu5o7Y9GK7NvhSvVNOLvwmNgL2dDkQg0QDLpOUp6OEth7SlldcJZq8226rHdUSIS8xMCifbHgwOvLGQCsBjN7annG4zCyrE/BPSqxzRm6G6o8k3Good69jYGih4KQ5MLHUZJmbDJrZrRBvsHNBOUObgLvyw/aM5PVIiXXH684cNmfK6alIPQE3Na0gshGXXEwuwp3O/MJLWOT5WsSM0SvWhObMHb2+VPi+Y+H+BBXaqwTamyyVF89ifxcqtS7Y0pQXpAEToKJkoKdHIv7E2rP6T4FweDGmuNxZJtM5NoWrbZXTqjKWZ3CK2+UhgIiuObVJwub4WIcX92KrQJ2JfZIsl3M88xLbYd9nk1r4GeJnuU+6CN7su51+DnDPl0OGWIPQnQ6y/aVKObijm7/QpeKRkCs2vONjaPfslgiID2pYSpQPiUad/ya++oic=
  on:
    tags: true
  distributions: "sdist"
  