name: MACS2 application

on:
  push:
    branches:
    - master
    - release_*
    - fix_*
    - hotfix_*
    - feat_*
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install MACS2
      run: |
        python setup.py install
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: Test with small data files
      run: |
        cd test
        ./test.sh subcommandtest
        flag=1;for i in `ls subcommandstest_run_*/*.log`;do echo $i;egrep -i "error|warning" $i;let "flag&=$?";done;if [[ $flag == 0 ]];then false;fi
        cd ..
    - name: Build sdist
      run: |
        python setup.py sdist
    - name: Publish distribution to PyPI
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}